### PR TITLE
Python XXE

### PR DESCRIPTION
**Pull request by GeekMasher**
There is both a remote flow query but also a simple "parser is insecure" query

### CODE REVIEW

**Comment by jorgectf** [comment]
I think you might want to check [this PR](https://github.com/github/codeql/pull/6112/files) out for some inspiration :)

**Comment by GeekMasher** [comment]
@jorgectf That is some awesome work and I must have missed it because it wasn't merged when I started creating this. Yours is FAR more evolved than my queries. I will be closing this once I have tested yours to make sure it covers my cases (which from a glance it will).

**Comment by zbazztian** [comment]
@GeekMasher Looks like you might be gravitating towards the queries Jorge wrote, so let me know if you still want this reviewed.

**Comment by GeekMasher** [comment]
As @zbazztian and I found out, the query by @jorgectf is still not released so we'll have to wait until the new version of CodeQL has the new query bundled in it.

**Comment by jorgectf** [comment]
Oh, I see it hasn't made it to `lgtm.com` branch yet. Anyway, it is still under `experimental/`, but I believe @RasmusWL (who did an outstanding work in the query) and the team is planning to promote it soon :)

**Comment by jorgectf** [comment]
FYI https://github.com/github/codeql/pull/8634

**Comment by jorgectf** [comment]
https://lgtm.com/rules/1515394699817/ & https://lgtm.com/rules/1515368549707/ 🎉

**Comment by RasmusWL** [comment]
@GeekMasher I did not add the "parsing is insecure" query, but it should be very easy to create one using the [`vulnerableTo` member-predicate of the `XmlParsing` concept](https://github.com/github/codeql/pull/8634/files#diff-d31b95d0643733e70ef7320bd131b75f31ea4a9701fd817781a438ef1a87a48dR540):+1:

**Comment by aegilops** [comment]
Do we want to continue with this?

Using this query could result in FPs _unless_ we can detect an old version of Python in use.

Modern versions of the underlying XML parsing library aren't vulnerable to this, and neither are modern versions of Python modules. The Pydoc around XML explains the situation.

**Comment by GeekMasher** [comment]
Closing this PR now

**Pull request closed without merging**
