### PR TITLE
Add LocalSources Support for future Go Queries

### PR DESCRIPTION
**Pull request by securingdev**
Need to add testing, but wanted to submit a draft pull request for Go LocalSources support.

### CODE REVIEW

**Comment by securingdev** [comment]
Adds support for #13 requested by @GeekMasher

**Comment by GeekMasher** [comment]
Awesome work! The only comment I'll make right now is that no query uses this library. We might need to create local variants for these certain queries.

https://github.com/advanced-security/codeql-queries/blob/geekmasher/go-local-variants/go/CWE-078/CodeInjectionLocal.ql

**Comment by securingdev** [comment]
> Awesome work! The only comment I'll make right now is that no query uses this library. We might need to create local variants for these certain queries.
> 
> https://github.com/advanced-security/codeql-queries/blob/geekmasher/go-local-variants/go/CWE-078/CodeInjectionLocal.ql

That's fair, this PR adds support for our ability to go about doing that - I'll rename the PR accordingly so that there isn't any confusion.

**Comment by securingdev** [comment]
In thinking a bit more about this, I may pair down the `LocalSources.ql` because it feels like some of these should be labeled as "Sinks" instead of sources. Would you agree @GeekMasher?

**Review by GeekMasher — APPROVED** [review]
Looking good

**Pull request merged**
