### PR TITLE
Unpinned Actions step query (not a SHA hash)

### PR DESCRIPTION
**Pull request by aegilops**
New query using Actions model in JavaScript to spot Actions steps using a version that isn't a pinned SHA-1 commit hash

### CODE REVIEW

**Comment by aegilops** [comment]
I tagged it "audit" since this will flag so many Actions workflow files it'd be overwhelming.

I also need to look at the severity - I just left it with the metadata from a different query and didn't think about it yet.

**Review by GeekMasher — APPROVED** [review]
Looks really good, nice work!

**Comment by aegilops** [comment]
Added tests, excluding trusted orgs, and QHelp and MarkDown now included.

Just need to think about severity now.

**Comment by aegilops** [comment]
I did a quick-and-dirty guess on a CVSS scoring page and got 8.0. Will do that later.

**Pull request merged**
