### PR TITLE
Update Customizations.qll

### PR DESCRIPTION
**Pull request by amitgupta7**
Adding Webgoat XSS Sinks

### CODE REVIEW

**Comment by GeekMasher** [comment]
@zbazztian Would be great for your review

**Comment by amitgupta7** [comment]
@zbazztian  can you please review adding XSS sinks to Customizations.qll so that xss query can be used as-is for webgoat. 
image

**Comment by zbazztian** [comment]
I had a [discussion](https://github.com/github/codeql/pull/7548#discussion_r781296586) with Tony Torralba from the security team about this a while ago. He argues, and I now tend to agree with him, that we shouldn't flag the XSS in WebGoat's Java code but rather in the JavaScript code. In the discussion he also gives a straightforward solution for how to implement this in the JavaScript query: i.e. by importing `AdditionalSources.qll` into JavaScript's `Customizations.qll`. I'd be in favor of doing that instead and see whether it suffices to detect the XSS in WebGoat's JS code.

**Comment by amitgupta7** [comment]
@zbazztian I think we need the entire dataflow shown as Issue with webgoat. Since there isn't a way to query the language boundary, the next best thing is to add this along with customisations to Javascript sources (see PR https://github.com/advanced-security/codeql-queries/pull/16).

**Comment by zbazztian** [comment]
It generally looks good to me. Have you tested this on WebGoat? It seems to me that this setup relies on the queries under https://github.com/advanced-security/codeql-queries/tree/main/java/CWE-079 to work. But those queries are specifically for detecting XSS in JSP code. I think it might be better to have a separate, generic customized XSS query

**Comment by zbazztian** [comment]
Did someone test whether those customizations are actually picked up from any query? I don't see `Customizations.qll` imported from anywhere.

**Comment by zbazztian** [comment]
@GeekMasher ^

**Comment by amitgupta7** [comment]
Closing this, since we may anyways need to recompile cache for these changes, hence easier to make these changes via the tools bundle. https://github.com/amitgupta7/demo-codeql-bundle

**Pull request closed without merging**
